accounts/urls.py
from django.urls import path
from .views import login_user, SignUpAsJobSeeker, logout_user, SignUpAsEmployee, profile, view_resume, update_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('employee-signup/', SignUpAsEmployee.as_view(), name='signup-employer'),
    path('jobseeker-signup/', SignUpAsJobSeeker.as_view(), name='signup-employee'),
    path('profile/<int:id>/', profile, name='profile'),
    path('view-resume/<int:id>/', view_resume, name='view-resume'),
    path('update-profile/<int:id>/', update_profile, name='update-profile')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import homepage, aboutus, contactus, testimonial


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('about/', aboutus, name='aboutus'),
    path('contact-us/', contactus, name='contactus'),
    path('testimonial/', testimonial, name='testimonial'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from abstract.base import BaseModel
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField


USER_TYPE = (
    ('job-seeker', 'Job Seeker'),
    ('employer', 'employer')
)

GENDER_CHOICE = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('Others', 'Others')
)


class User(AbstractUser):
    email = models.EmailField(unique=True, error_messages={
                              'unique': 'User with that email already exist.'})
    gender = models.CharField(max_length=6, choices=GENDER_CHOICE)
    bio = models.TextField()
    address = models.CharField(max_length=100)
    mobile = models.CharField(max_length=10)
    role = models.CharField(
        max_length=10, default='job-seeker', choices=USER_TYPE)
    profile_pic = models.ImageField(
        upload_to='profiles', blank=True, null=True)

    def __str__(self):
        return f"{self.email} - user created."

    @property
    def job_applied(self):
        return self.applicant.all()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


def validete_file_size(value):
    max_size = 5*1024*1024
    if value.size > max_size:
        raise ValidationError('File size mustnot exceed 5MB.')


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    experience = RichTextField()
    skill = RichTextField()
    github_url = models.URLField(null=True, blank=True)
    portfolio_url = models.URLField(null=True, blank=True)
    resume = models.FileField(upload_to='resume', validators=[
                              FileExtensionValidator(['pdf', 'docx']), validete_file_size])

    def __str__(self):
        return f"{self.user.username} profile created"

    class Meta:
        ordering = ('-updated',)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=200)
    password = forms.CharField(
        label='password', max_length=200, widget=forms.PasswordInput())


class EmployeeRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1',
                  'password2', 'gender', 'bio', 'address', 'mobile', 'profile_pic')

    def save(self, commit: bool = True):
        user = super().save(commit=False)
        user.role = 'employer'
        if commit:
            user.save()
        return user


class JobSeekerRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1',
                  'password2', 'gender', 'bio', 'address', 'mobile', 'profile_pic')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = 'job-seeker'
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    experience = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 80}))
    skill = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 80}))

    class Meta:
        model = Profile
        exclude = ('user',)

accounts/views.py
from typing import Any
import os
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView
from django.contrib import messages
from django.contrib.auth import get_user_model
from .forms import LoginForm, EmployeeRegistrationForm, JobSeekerRegistrationForm, UpdateProfileForm
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from jobs.models import JobApplication
from django.db.models import Q


User = get_user_model()


def login_user(request):
    if (request.user.is_authenticated):
        return redirect('homepage')
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if user.role == 'employer':
                    return redirect('jobs:dashboard')
                else:
                    return redirect('/')
            messages.error(
                request, "Invalid username or password. Try Again...")

    return render(request, 'login.html', {'form': form})


class SignUpAsEmployee(CreateView):
    model = User
    form_class = EmployeeRegistrationForm
    template_name = 'signup.html'
    success_url = '/accounts/login'
    extra_content = {'title': 'Employer Registration'}

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = self.form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password1')
            user.set_password(password)
            user.save()
            return redirect('accounts:login')
        return render(request, 'signup.html', {'form': form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_content'] = self.extra_content
        return context


class SignUpAsJobSeeker(CreateView):
    model = User
    form_class = JobSeekerRegistrationForm
    template_name = 'signup.html'
    success_url = '/accounts/login'
    extra_content = {'title': 'JobSeeker Registration'}

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = self.form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password1')
            user.set_password(password)
            user.save()
            return redirect('accounts:login')
        return render(request, 'signup.html', {'form': form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_content'] = self.extra_content
        return context


@login_required()
def logout_user(request):
    logout(request)
    return redirect('accounts:login')


@login_required()
def profile(request, id):
    try:
        user = User.objects.get(id=id)
        profile = Profile.objects.get(user=user)
        return render(request, 'profile.html', {'profile': profile})
    except User.DoesNotExist:
        print("User Doesnot exist")

    except User.MultipleObjectsReturned:
        print("Multiple Objects Returned")
    except:
        print('Something went wrong.')


@login_required()
def view_resume(request, id):
    profile = get_object_or_404(Profile, id=id)
    file_path = profile.resume.path
    if os.path.exists(file_path):
        with open(file_path, 'rb') as pdf_file:
            response = HttpResponse(pdf_file, content_type='application/pdf')
            return response
    return render(request, '404.html')


@login_required()
def update_profile(request, id):
    user = get_object_or_404(User, id=id)
    profile = get_object_or_404(Profile, user=user)
    form = UpdateProfileForm(instance=profile)
    if request.method == "POST":
        form = UpdateProfileForm(
            request.POST, files=request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile', args=[id]))
    return render(request, 'update-profile.html', {'form': form})

accounts/templates/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Login</h1>
    </div>
</div>
<!-- Header End -->
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-4">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">Login</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock content %}

</form>

accounts/templates/profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Profile</h1>
    </div>
</div>
<!-- Header End -->
<!-- end of modal  -->
{% if profile.experience %}
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img src="{{profile.user.profile_pic.url}}" alt="avatar" class="rounded-circle img-fluid"
                            style="width: 150px;">
                        <h5 class="my-3">{{profile.user.full_name}}</h5>
                        <p class="text-muted mb-1">{{profile.user.bio}}</p>
                        <p class="text-muted mb-4">{{profile.user.email}}</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body p-0">
                    </div>
                </div>
            </div>

            <div class="col-lg-8">
                {% if request.user.role == 'employer' %}
                <div style="position: relative; bottom: 20px; left: 550px;">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Application Status
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" name='accept' value='accepted' href="#">Accept</a></li>
                            <li><a class="dropdown-item" name="reject" value='rejected' href="#">Reject</a></li>
                        </ul>
                    </div>
                </div>
                {%endif%}
                <div class="card mb-4">

                    <div class="card-body">
                        <div class="mt-3">
                            <h4>Experience</h4>
                            <p>{{profile.experience | safe}}</p>
                        </div>
                        <div class="mt-3">
                            <h4>Skills</h4>
                            <p>{{profile.skill | safe}}</p>
                        </div>
                        <div class="mt-3">
                            <h4>Resume</h4>
                            <a href="{% url 'accounts:view-resume' profile.id%}" target="_blank"
                                class="btn btn-primary">View Resume</a>
                            <a href="{{profile.resume.url}}" download class="btn btn-warning">Download
                                Resume</a>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{%else%}
<p class="ms-3 text-center text-danger">Please Complete Your Profile.</p>
{%endif%}

{% endblock content %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">{{ extra_content.title }}</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-6">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">Register</button>
                </div>

            </form>
            <div class="m-4">
                <p>Already have an account? <a href="{% url 'accounts:login'%}">Login</a></p>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

</form>

accounts/templates/update-profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">Update Profile</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-6">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">Update Profile</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock content %}

</form>