accounts/urls.py
from django.urls import path
from .views import login_user, SignUpAsJobSeeker, logout_user, SignUpAsEmployee, profile, view_resume, update_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('employee-signup/', SignUpAsEmployee.as_view(), name='signup-employer'),
    path('jobseeker-signup/', SignUpAsJobSeeker.as_view(), name='signup-employee'),
    path('profile/<int:id>/', profile, name='profile'),
    path('view-resume/<int:id>/', view_resume, name='view-resume'),
    path('update-profile/<int:id>/', update_profile, name='update-profile')
]

jobs/urls.py
from django.urls import path, include
from .views import (JobListPageView,  job_detail_view, apply_job, my_jobs_list, search_job,
                    CreateJob, ViewMyJobPosted, delete_job, UpdateJob, PostTesimonials, ApplicantListPageView)
from src.views import homepage
app_name = 'jobs'

urlpatterns = [
    path('', JobListPageView.as_view(), name='job'),
    path('job/<int:id>/', job_detail_view, name='job-detail'),
    path('apply/<int:job_id>/', apply_job, name='apply_job'),
    path('myjobs/', my_jobs_list, name='my_jobs'),
    path('search/', search_job, name='search_job'),
    path('create-testimonial/', PostTesimonials.as_view(),
         name='create-testimonial'),
    path('employer/dashboard/',
         include(
             [
                 path('', homepage, name='dashboard'),
                 path('post-job', CreateJob.as_view(), name='post-job'),
                 path('my-jobs', ViewMyJobPosted.as_view(), name='job-posted'),
                 path('delete-job/<int:id>/', delete_job, name='delete-job'),
                 path('update-job/<int:pk>/',
                      UpdateJob.as_view(), name='update-job'),
                 path('<int:pk>/applicants/',
                      ApplicantListPageView.as_view(), name='applicant-list')
             ]
         )
         ),
    path('new-job/', CreateJob.as_view(), name='create-job')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import homepage, aboutus, contactus, testimonial


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('about/', aboutus, name='aboutus'),
    path('contact-us/', contactus, name='contactus'),
    path('testimonial/', testimonial, name='testimonial'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/about.html
{% extends "base.html" %}

{% load static%}

{% block content %}

<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
    </div>
</div>
<!-- Header End -->


<!-- About Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 align-items-center">
            <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                <div class="row g-0 about-bg rounded overflow-hidden">
                    <div class="col-6 text-start">
                        <img class="img-fluid w-100" src="{%static 'img/about-1.jpg'%}">
                    </div>
                    <div class="col-6 text-start">
                        <img class="img-fluid" src="{%static 'img/about-2.jpg'%}" style="width: 85%; margin-top: 15%;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid" src="{%static 'img/about-3.jpg'%}" style="width: 85%;">
                    </div>
                    <div class="col-6 text-end">
                        <img class="img-fluid w-100" src="{%static 'img/about-4.jpg'%}">
                    </div>
                </div>
            </div>
            <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                <p class="mb-4"> Our platform is a dynamic space designed to bridge the gap between talent
                    and employers, facilitating seamless matches that propel careers forward. We pride
                    ourselves on providing a user-friendly experience, empowering job seekers with intuitive
                    tools and comprehensive resources. Whether you're a seasoned professional or embarking on
                    your career journey, careerforge is your dedicated partner, committed to unlocking doors
                    to a world of possibilities. Join us in shaping the future of your career.</p>
                <p><i class="fa fa-check text-primary me-3"></i>Comprehensive Job Listings</p>
                <p><i class="fa fa-check text-primary me-3"></i>User-Friendly Interface</p>
                <p><i class="fa fa-check text-primary me-3"></i>Customized Job Alerts</p>
            </div>
        </div>
    </div>
</div>
<!-- About End -->
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>careerForge</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link
            href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap"
            rel="stylesheet">

        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css'%}" rel="stylesheet">
    </head>

    <body>
        <div class="container-xxl bg-white p-0">
            <!-- Spinner Start -->
            <div id="spinner"
                class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
                <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            <!-- Spinner End -->


            {%include 'navbar.html'%}
            {%block content%}
            {%endblock%}


            <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
                <div class="container py-5">
                    <div class="row g-5">
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-white mb-4">Company</h5>
                            <a class="btn btn-link text-white-50" href="">About Us</a>
                            <a class="btn btn-link text-white-50" href="">Contact Us</a>
                            <a class="btn btn-link text-white-50" href="">Our Services</a>
                            <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                            <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-white mb-4">Quick Links</h5>
                            <a class="btn btn-link text-white-50" href="">About Us</a>
                            <a class="btn btn-link text-white-50" href="">Contact Us</a>
                            <a class="btn btn-link text-white-50" href="">Our Services</a>
                            <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                            <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-white mb-4">Contact</h5>
                            <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                            <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                            <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                            <div class="d-flex pt-2">
                                <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i
                                        class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                                <a class="btn btn-outline-light btn-social" href=""><i
                                        class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6">
                            <h5 class="text-white mb-4">Newsletter</h5>
                            <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                            <div class="position-relative mx-auto" style="max-width: 400px;">
                                <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text"
                                    placeholder="Your email">
                                <button type="button"
                                    class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="copyright">
                        <div class="row">
                            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                                &copy; <a class="border-bottom" href="#">careerForge</a>, All Right Reserved.

                                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                                Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                                </br>Distributed By <a class="border-bottom" href="https://themewagon.com"
                                    target="_blank">ThemeWagon</a>
                            </div>
                            <div class="col-md-6 text-center text-md-end">
                                <div class="footer-menu">
                                    <a href="">Home</a>
                                    <a href="">Cookies</a>
                                    <a href="">Help</a>
                                    <a href="">FQAs</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->


            <!-- Back to Top -->
            <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{%static 'lib/wow/wow.min.js'%}"></script>
        <script src="{%static 'lib/easing/easing.min.js'%}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js'%}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js'%}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js'%}"></script>
    </body>

</html>

templates/index.html
       {% extends "base.html" %}
       {% load static %}
       {% block content %}
       {% for message in messages %}
       <div class="alert alert-danger" role="alert">
           {{message}}
       </div>
       {%endfor%}
       <!-- Carousel Start -->
       <div class="container-fluid p-0">
           <div class="owl-carousel header-carousel position-relative">
               <div class="owl-carousel-item position-relative">
                   <img class="img-fluid" src="{%static 'img/carousel-1.jpg'%}" alt="">
                   <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center"
                       style="background: rgba(43, 57, 64, .5);">
                       <div class="container">
                           <div class="row justify-content-start">
                               <div class="col-10 col-lg-8">
                                   <h1 class="display-3 text-white animated slideInDown mb-4">Find The Perfect Job That
                                       You Deserved</h1>
                                   <p class="fs-5 fw-medium text-white mb-4 pb-2">Unlock Your Future: Connecting Talent
                                       to Opportunities.</p>
                                   <a href="" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Search A
                                       Job</a>
                                   <a href="" class="btn btn-secondary py-md-3 px-md-5 animated slideInRight">Find A
                                       Talent</a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
               <div class="owl-carousel-item position-relative">
                   <img class="img-fluid" src="{%static 'img/carousel-2.jpg'%}" alt="">
                   <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center"
                       style="background: rgba(43, 57, 64, .5);">
                       <div class="container">
                           <div class="row justify-content-start">
                               <div class="col-10 col-lg-8">
                                   <h1 class="display-3 text-white animated slideInDown mb-4">Find The Best Startup Job
                                       That Fit You</h1>
                                   <p class="fs-5 fw-medium text-white mb-4 pb-2">Your Gateway to Career Success:
                                       Navigate, Apply, Achieve.</p>
                                   <a href="" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Search A
                                       Job</a>
                                   <a href="" class="btn btn-secondary py-md-3 px-md-5 animated slideInRight">Find A
                                       Talent</a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
       <!-- Carousel End -->


       <!-- Search Start -->
       <div class="container-fluid bg-primary mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
           <div class="container">
               <form method="post" action="{%url 'jobs:search_job'%}">
                   {%csrf_token%}
                   <div class="row g-2">
                       <div class="col-md-10">

                           <div class="row g-2">
                               <div class="col-md-4">
                                   <input type="text" name="title" class="form-control border-0"
                                       placeholder="Keyword" />
                               </div>
                               <div class="col-md-4">
                                   <select name="category" class="form-select border-0">
                                       <option selected>Category</option>
                                       {% for category in categories %}
                                       <option name="category" value={{category.id}}>{{category.title}}</option>
                                       {%endfor%}

                                   </select>
                               </div>
                               <div class="col-md-4">
                                   <input type="text" name="location" class="form-control border-0"
                                       placeholder="Location" />
                               </div>
                           </div>

                       </div>
                       <div class="col-md-2">
                           <button class="btn btn-dark border-0 w-100" type="submit">Search</button>
                       </div>
                   </div>
               </form>
           </div>
       </div>
       <!-- Search End -->

       <!-- Jobs Start -->
       {% if jobs %}
       <div class="container-xxl py-5">
           <div class="container">
               <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Available Jobs</h1>
               <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
                   <div class="tab-content">
                       <div id="tab-1" class="tab-pane fade show p-0 active">
                           <div class="job-item p-4 mb-4">
                               <div class="row g-4">
                                   {% for job in jobs %}
                                   <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                       <img class="flex-shrink-0 img-fluid border rounded"
                                           src="{{job.company_logo.url}}" alt="" style="width: 80px; height: 80px;">
                                       <div class="text-start ps-4">
                                           <h5 class="mb-3">{{job.title}}</h5>
                                           <span class="text-truncate me-3"><i
                                                   class="fa fa-map-marker-alt text-primary me-2"></i>{{job.location}}</span>
                                           <span class="text-truncate me-3"><i
                                                   class="far fa-clock text-primary me-2"></i>{{job.type}}</span>
                                           <span class="text-truncate me-0"><i
                                                   class="far fa-money-bill-alt text-primary me-2"></i>${{job.min_salary}}
                                               -
                                               ${{job.max_salary}}</span>
                                       </div>
                                   </div>

                                   <div
                                       class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                       <div class="d-flex mb-3">
                                           <a class="btn btn-light btn-square me-3" href="{{job.get_absolute_url}}"><i
                                                   class="far fa-heart text-primary"></i></a>
                                           <a class="btn btn-primary" href="{{job.get_absolute_url}}">Detail</a>
                                       </div>
                                       <small class="text-truncate"><i
                                               class="far fa-calendar-alt text-primary me-2"></i>Deadline:
                                           {{job.deadline}}</small>
                                   </div>
                                   {%endfor%}
                               </div>
                           </div>


                       </div>
                   </div>
               </div>
           </div>

           {%endif%}
           <!-- Jobs End -->



           <!-- Category Start -->
           <div class="container-xxl py-5">
               <div class="container">
                   <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Explore By Category</h1>
                   <div class="row g-4">
                       {% for category in categories %}
                       <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                           <a class="cat-item rounded p-4" href="">
                               <i class="{{category.i_class}}"></i>
                               <h6 class="mb-3">{{category.title}}</h6>
                               <p class="mb-0">{{category.count_vacancy}} Vacancy</p>
                           </a>
                       </div>
                       {%endfor%}


                   </div>
               </div>
           </div>
           <!-- Category End -->


           <!-- About Start -->
           <div class="container-xxl py-5">
               <div class="container">
                   <div class="row g-5 align-items-center">
                       <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                           <div class="row g-0 about-bg rounded overflow-hidden">
                               <div class="col-6 text-start">
                                   <img class="img-fluid w-100" src="{%static 'img/about-1.jpg'%}">
                               </div>
                               <div class="col-6 text-start">
                                   <img class="img-fluid" src="{%static 'img/about-2.jpg'%}"
                                       style="width: 85%; margin-top: 15%;">
                               </div>
                               <div class="col-6 text-end">
                                   <img class="img-fluid" src="{%static 'img/about-3.jpg'%}" style="width: 85%;">
                               </div>
                               <div class="col-6 text-end">
                                   <img class="img-fluid w-100" src="{%static 'img/about-4.jpg'%}">
                               </div>
                           </div>
                       </div>
                       <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                           <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                           <p class="mb-4"> Our platform is a dynamic space designed to bridge the gap between talent
                               and employers, facilitating seamless matches that propel careers forward. We pride
                               ourselves on providing a user-friendly experience, empowering job seekers with intuitive
                               tools and comprehensive resources. Whether you're a seasoned professional or embarking on
                               your career journey, careerforge is your dedicated partner, committed to unlocking doors
                               to a world of possibilities. Join us in shaping the future of your career.</p>
                           <p><i class="fa fa-check text-primary me-3"></i>Comprehensive Job Listings</p>
                           <p><i class="fa fa-check text-primary me-3"></i>User-Friendly Interface</p>
                           <p><i class="fa fa-check text-primary me-3"></i>Customized Job Alerts</p>
                       </div>
                   </div>
               </div>
           </div>
           <!-- About End -->




           <!-- Testimonial Start -->
           <div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
               <div class="container">
                   <h1 class="text-center mb-5">Our Clients Say!!!</h1>

                   <div class="owl-carousel testimonial-carousel">
                       {% for testimonial in testimonials %}
                       <div class="testimonial-item bg-light rounded p-4">
                           <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                           <p>{{testimonial.content}}</p>
                           <div class="d-flex align-items-center">
                               <img class="img-fluid flex-shrink-0 rounded" src="{{testimonial.user.profile_pic.url}}"
                                   style="width: 50px; height: 50px;">
                               <div class="ps-3">
                                   <h5 class="mb-1">{{testimonial.user.username}}</h5>
                                   <small>Profession</small>
                               </div>
                           </div>
                       </div>
                       {%endfor%}
                   </div>

               </div>
           </div>

           {% endblock content %}
           <!-- Testimonial End -->

templates/navbar.html
{% load nav_tags %}

<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="{% url 'homepage'%}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
        <h1 class="m-0 text-primary">CareerForge</h1>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{%url 'homepage'%}" class="nav-item nav-link {% is_active 'homepage' %}">Home</a>
            <a href="{% url 'aboutus'%}" class="nav-item nav-link {% is_active 'aboutus' %}">About</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                <div class="dropdown-menu rounded-0 m-0">
                    {% if request.user.is_authenticated and request.user.role == "employer"  %}
                    <a href="{% url 'jobs:post-job'%}" class="dropdown-item {% is_active 'post-job' %}">Post Job</a>
                    <a href="{% url 'jobs:job-posted'%}" class="dropdown-item">My Jobs</a>
                    {% else %}
                    <a href="{% url 'jobs:job'%}" class="dropdown-item {% is_active 'job' %}">Job Lists</a>
                    <a href="{% url 'jobs:my_jobs'%}" class="dropdown-item">My Jobs</a>
                    {% endif %}
                </div>
            </div>
            <a href="{% url 'contactus'%}" class="nav-item nav-link {% is_active 'contactus' %}">Contact</a>

            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Testimonial</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{% url 'jobs:create-testimonial'%}" class="dropdown-item">Create</a>
                    <a href="{% url 'testimonial'%}" class="dropdown-item">View</a>
                </div>
            </div>

            {% if request.user.is_anonymous %}
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Register</a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{%url 'accounts:signup-employee'%}" class="dropdown-item">Job Seeker</a>
                    <a href="{% url 'accounts:signup-employer'%}" class="dropdown-item">Employer</a>
                </div>
            </div>
            {% endif %}


        </div>
        {% if request.user.is_anonymous %}
        <a href="{% url 'accounts:login'%}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Login<i
                class="fa fa-arrow-right ms-3"></i></a>
        {%else%}


        <div class="nav-item dropdown">
            <a class="rounded-0 py-1 px-lg-5 d-none d-lg-block" href="#">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    <img src="{{profile_pic.url}}" alt="{{request.user.username}}" width="30" class="rounded-pill">
                    <span>{{request.user.username}}</span>
                </a>
                <div class="dropdown-menu rounded-0 m-0">
                    <a href="{%url 'accounts:profile' request.user.id %}" class="dropdown-item">View Profile</a>
                    <a href="{% url 'accounts:update-profile' request.user.id%}" class="dropdown-item">Update
                        Profile</a>
                </div>
        </div>
        </a>
        <a href="{%url 'accounts:logout'%}" class="btn btn-danger rounded-0 py-4 px-lg-5 d-none d-lg-block"
            role="button" aria-disabled="true">Logout</a>
        {%endif%}
    </div>
</nav>
<!-- Navbar End -->

templates/testimonial.html
{% extends "base.html" %}

{%load static%}
{% block content %}
<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Testimonial</h1>
    </div>
</div>
<!-- Header End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <h1 class="text-center mb-5">Our Clients Say!!!</h1>

        <div class="owl-carousel testimonial-carousel">
            {% for testimonial in testimonials %}
            <div class="testimonial-item bg-light rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>{{testimonial.content}}</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded" src="{{testimonial.user.profile_pic.url}}"
                        style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">{{testimonial.user.username}}</h5>
                        <small>Profession</small>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>

    </div>
</div>
<!-- Testimonial End -->
{% endblock content %}