accounts/urls.py
from django.urls import path
from .views import login_user, SignUpAsJobSeeker, logout_user, SignUpAsEmployee, profile, view_resume, update_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('employee-signup/', SignUpAsEmployee.as_view(), name='signup-employer'),
    path('jobseeker-signup/', SignUpAsJobSeeker.as_view(), name='signup-employee'),
    path('profile/<int:id>/', profile, name='profile'),
    path('view-resume/<int:id>/', view_resume, name='view-resume'),
    path('update-profile/<int:id>/', update_profile, name='update-profile')
]

jobs/urls.py
from django.urls import path, include
from .views import (JobListPageView,  job_detail_view, apply_job, my_jobs_list, search_job,
                    CreateJob, ViewMyJobPosted, delete_job, UpdateJob, PostTesimonials, ApplicantListPageView)
from src.views import homepage
app_name = 'jobs'

urlpatterns = [
    path('', JobListPageView.as_view(), name='job'),
    path('job/<int:id>/', job_detail_view, name='job-detail'),
    path('apply/<int:job_id>/', apply_job, name='apply_job'),
    path('myjobs/', my_jobs_list, name='my_jobs'),
    path('search/', search_job, name='search_job'),
    path('create-testimonial/', PostTesimonials.as_view(),
         name='create-testimonial'),
    path('employer/dashboard/',
         include(
             [
                 path('', homepage, name='dashboard'),
                 path('post-job', CreateJob.as_view(), name='post-job'),
                 path('my-jobs', ViewMyJobPosted.as_view(), name='job-posted'),
                 path('delete-job/<int:id>/', delete_job, name='delete-job'),
                 path('update-job/<int:pk>/',
                      UpdateJob.as_view(), name='update-job'),
                 path('<int:pk>/applicants/',
                      ApplicantListPageView.as_view(), name='applicant-list')
             ]
         )
         ),
    path('new-job/', CreateJob.as_view(), name='create-job')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import homepage, aboutus, contactus, testimonial


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('about/', aboutus, name='aboutus'),
    path('contact-us/', contactus, name='contactus'),
    path('testimonial/', testimonial, name='testimonial'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

jobs/models.py
from django.db import models
from django.urls import reverse
from abstract.base import BaseModel
from django.conf import settings
from ckeditor.fields import RichTextField

JOB_TYPES = (
    ('full-time', 'Full Time'),
    ('part-time', 'Part Time'),
    ('contract', 'Contract'),
    ('permanent', 'permanent')
)

JOB_APPLICATION_STATUS = (
    ('pending', 'Pending'),
    ('accepted', 'Accepted'),
    ('rejected', 'Rejected')
)

JOB_STATUS = (
    ('active', 'active'),
    ('inactive', 'inactive'),
    ('filled', 'filled')
)


class Category(BaseModel):
    title = models.CharField(max_length=200, unique=True)
    i_class = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ('-updated',)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return f"{self.title}"

    @property
    def count_vacancy(self):
        jobs = self.job_set.all()
        count = 0
        for job in jobs:
            count += job.vacancy
        return count


class Job(BaseModel):
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=10, choices=JOB_TYPES)
    descriptions = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    requirements = RichTextField()
    location = models.CharField(max_length=200, blank=True)
    application_count = models.IntegerField(default=0)
    contact_email = models.EmailField()
    status = models.CharField(max_length=9, choices=JOB_STATUS)
    featured_job = models.BooleanField(default=False)
    urgently_hiring = models.BooleanField(default=False)
    min_salary = models.FloatField(default=0.0)
    max_salary = models.FloatField(default=0.0)
    deadline = models.DateField()
    vacancy = models.IntegerField(default=1)
    company_name = models.CharField(max_length=200, blank=True)
    company_website = models.URLField(blank=True, null=True)
    company_logo = models.ImageField(upload_to='company_logo')
    hiring_person = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse("jobs:job-detail", kwargs={"id": self.id})

    @property
    def application_received(self):
        return self.jobs.all()

    class Meta:
        ordering = ('-updated',)

    def __str__(self) -> str:
        return f"{self.title} - job has been created."


class JobApplication(BaseModel):
    applicant = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applicant')
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='jobs')
    status = models.CharField(
        max_length=8, choices=JOB_APPLICATION_STATUS, default='pending')

    def __str__(self):
        return f"{self.applicant.username} has applied for {self.job.title}"

    class Meta:
        ordering = ('-updated',)


class Testimonials(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    content = models.TextField()

    class Meta:
        ordering = ('-updated',)
        verbose_name_plural = "Testimonials"

    def __str__(self):
        return f"{self.user.username} has posted testimonials."

jobs/forms.py
from typing import Any
from django import forms
from django.forms import ModelForm
from .models import Job, Testimonials, JobApplication


class SearchForm(ModelForm):
    class Meta:
        model = Job
        fields = ('title', 'category', 'location')


class PostJobForm(ModelForm):
    requirements = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 80}))

    class Meta:
        model = Job
        exclude = ('application_count', 'hiring_person', 'status')


class UpdateJobForm(ModelForm):
    requirements = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'cols': 80}))

    class Meta:
        model = Job
        exclude = ('application_count', 'hiring_person')


class TestimonialForm(ModelForm):
    class Meta:
        model = Testimonials
        exclude = ('user',)


class ApplicationStatusForm(ModelForm):
    class Meta:
        model = JobApplication
        exclude = ('job', 'applicant')

jobs/views.py
from typing import Any
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.db.models import Q
from datetime import datetime
from .models import Job, JobApplication, Testimonials
from .forms import SearchForm, PostJobForm, UpdateJobForm, TestimonialForm, ApplicationStatusForm


User = get_user_model()
# Create your views here.


class JobListPageView(ListView):
    model = Job
    template_name = 'job-list.html'
    context_object_name = 'jobs'
    # paginate_by = 3

    def get_queryset(self):
        qs = Job.objects.filter(Q(status='active') and Q(
            deadline__gt=datetime.now()))
        return qs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Available Jobs'
        return context


def job_detail_view(request, id):
    job = get_object_or_404(Job, id=id)
    already_applied = False
    if request.user.is_authenticated:
        jobs_ = JobApplication.objects.select_related(
            'job').filter(applicant=request.user)
        for job_ in jobs_:
            if job == job_.job:
                already_applied = True
                break
    return render(request, 'job-detail.html', {'job': job, 'applied': already_applied})


@login_required(login_url='/accounts/login')
def apply_job(request, job_id):
    try:
        job_ = get_object_or_404(Job, id=job_id)
        JobApplication.objects.create(
            applicant=request.user, job=job_)
        job_.save()
        messages.success(request, "Job Applied.")
    except Exception as e:
        print(e)
        messages.error(request, 'Something went wrong. Try Again later...')
    return redirect('jobs:job-detail', id=job_id)


@login_required(login_url='/accounts/login')
def my_jobs_list(request):
    applications = JobApplication.objects.select_related(
        'job').filter(applicant=request.user)

    return render(request, 'my-job-list.html', {'applications': applications, 'title': 'My Jobs'})


def search_job(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            category = form.cleaned_data.get('category')
            location = form.cleaned_data.get('location')
            jobs = Job.objects.filter(Q(title__icontains=title), Q(category=category), Q(location__icontains=location), Q(status='active'), Q(
                deadline__gt=datetime.now()))
            return render(request, 'index.html', {'jobs': jobs})
        messages.error(request, 'Something went wrong. Try Again')
    return render(request, 'index.html')


class CreateJob(LoginRequiredMixin, CreateView):
    model = Job
    form_class = PostJobForm
    template_name = 'post-job.html'
    context_object_name = 'form'
    success_url = reverse_lazy('jobs:myjobs')

    def post(self, request, *args, **kwargs):
        form = self.form_class(self.request.POST, files=self.request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.hiring_person = self.request.user
            instance.save()
            return redirect('jobs:my_jobs')
        return render(request, 'post-job.html', {'form': form})

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create Job'
        context['btn_name'] = 'Create'
        return context


class UpdateJob(LoginRequiredMixin, UpdateView):
    model = Job
    form_class = UpdateJobForm
    template_name = 'post-job.html'
    context_object_name = 'form'
    success_url = reverse_lazy('jobs:myjobs')

    def post(self, request, *args, **kwargs):
        form = self.form_class(
            self.request.POST, files=self.request.FILES, instance=self.get_object())
        if form.is_valid():
            instance = form.save(commit=False)
            instance.hiring_person = self.request.user
            instance.save()
            return redirect('jobs:job-posted')
        return render(request, 'post-job.html', {'form': form})

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Job Information'
        context['btn_name'] = 'Update'
        return context


@login_required()
def delete_job(request, id):
    get_object_or_404(Job, id=id).delete()
    messages.success(request, 'Job Deleted Successfully')
    return redirect('jobs:job-posted')


class ViewMyJobPosted(LoginRequiredMixin, ListView):
    model = Job
    template_name = 'job-list.html'
    context_object_name = 'jobs'
    # paginate_by = 3

    def get_queryset(self):
        qs = Job.objects.filter(hiring_person=self.request.user)
        return qs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Jobs Posted'
        return context


class PostTesimonials(LoginRequiredMixin, CreateView):
    model = Testimonials
    form_class = TestimonialForm
    success_url = 'testimonial'
    template_name = 'testimonial-form.html'

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = self.form_class(self.request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = self.request.user
            instance.save()
            return redirect('testimonial')
        return render(request, 'testimonial-form.html', {'form': form})


class ApplicantListPageView(ListView):
    model = Job
    template_name = 'applicant-list.html'
    context_object_name = 'applicants'
    # paginate_by = 3

    def get_queryset(self):
        qs = get_object_or_404(Job, id=self.kwargs.get('pk'))
        return qs


class ApplicationStatusUpdateView(UpdateView):
    model = JobApplication
    form_class = ApplicationStatusForm
    success_url = reverse_lazy('/')
    context_object_name = 'form'
    template_name = 'profile.html'


# def change_application_update(request, job_id):
#     job = get_object_or_404(JobApplication, job_id)

jobs/templates/applicant-list.html
{% extends "base.html" %}
{% load static %}

{% block content %}



<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">Applicant List</h1>
    </div>
</div>
<!-- Header End -->


<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Applicants</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    <div class="job-item p-4 mb-4">
                        <div class="row g-4">
                            {% for application in applicants.application_received %}
                            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid border rounded"
                                    src="{{application.applicant.profile_pic.url}}" alt=""
                                    style="width: 80px; height: 80px;">
                                <div class="text-start ps-4">
                                    <h5 class="mb-3">{{application.applicant.username}}</h5>
                                    <span class="text-truncate me-3"><i
                                            class="fa fa-envelope-open text-primary me-2"></i>{{application.applicant.email}}</span>
                                    <span class="text-truncate me-3"><i
                                            class="fa fa-phone-alt text-primary me-2"></i>{{application.applicant.mobile}}</span>
                                    <span class="text-truncate me-3"><i
                                            class="fas fa-exclamation-triangle text-primary me-2"></i>
                                        {{application.status}}
                                    </span>
                                </div>
                            </div>

                            <div
                                class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                <div class="d-flex mb-3">

                                    <a class="btn btn-primary"
                                        href="{% url 'accounts:profile' application.applicant.id%}">View Profile</a>
                                </div>
                                <small class="text-truncate"><i
                                        class="far fa-calendar-alt text-primary me-2"></i>Applied:
                                    {{application.created}}</small>
                            </div>
                            {%endfor%}
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Jobs End -->
    {% endblock content %}

jobs/templates/job-detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<!-- Job Detail Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
        {{message}}
    </div>
    {%endfor%}
    <div class="container">
        <div class="row gy-5 gx-4">
            <div class="col-lg-8">
                <div class="d-flex align-items-center mb-5">
                    <img class="flex-shrink-0 img-fluid border rounded" src="{{job.company_logo.url}}" alt=""
                        style="width: 80px; height: 80px;">
                    <div class="text-start ps-4">
                        <h3 class="mb-3">{{job.title}}
                        </h3>
                        <span class="text-truncate me-3"><i
                                class="fa fa-map-marker-alt text-primary me-2"></i>{{job.location}}</span>
                        <span class="text-truncate me-3"><i
                                class="far fa-clock text-primary me-2"></i>{{job.type}}</span>
                        <span class="text-truncate me-0"><i
                                class="far fa-money-bill-alt text-primary me-2"></i>${{job.min_salary}} -
                            ${{job.max_salary}}</span>
                    </div>
                </div>

                <div class="mb-5">
                    <h4 class="mb-3">Job description</h4>
                    <p>{{job.descriptions}}</p>
                    <h4 class="mb-3">Requirements</h4>
                    {{job.requirements | safe}}
                </div>
                {% if request.user.role == 'employer'%}
                <div class="">
                    <h4 class="mb-4">Actions</h4>
                    <a class="btn btn-info" href="{%url 'jobs:update-job' job.id%}">Update</a>
                    <a href="{% url 'jobs:delete-job' job.id %}" class="btn btn-danger">Delete</a>
                </div>


                {%else%}


                <div class="">
                    <h4 class="mb-4">Apply For The Job</h4>
                    {% if not applied %}
                    <a class="btn btn-danger" href="{%url 'jobs:apply_job' job.id%}">Apply</a>
                    {%else%}
                    <button class="btn btn-info" disabled>Already Applied</button>
                    {%endif%}
                </div>
                {%endif%}
            </div>

            <div class="col-lg-4">
                {% if request.user.is_authenticated and request.user.role == 'employer'%}
                <div class="p-5 mb-4">
                    <a class="btn btn-info" href="{%url 'jobs:applicant-list' job.id%}">View Applicant</a>
                </div>
                {%endif%}
                <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                    <h4 class="mb-4">Job Summery</h4>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Published On: {{job.updated | date}}</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Vacancy: {{job.vacancy}}</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: {{job.type}}</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Applied By: {{job.application_count}}</p>
                    <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Deadline: {{job.deadline}}</p>
                    <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Status:

                        <button
                            class="btn {% if job.status == 'active' %}btn-primary{%else%} btn-danger{%endif%} btn-sm">{{job.status}}</button>
                    </p>
                </div>

                <div class="bg-light rounded p-5 wow slideInUp" data-wow-delay="0.1s">
                    <h4 class="mb-4">Company Detail</h4>
                    <p class="m-0">
                        <a href="{{job.company_website}}" target="_blank">{{job.company_website}}</a>
                    </p>
                    <p class="m-0">
                        <a href="mailto:{{job.company_website}}">{{job.contact_email}}</a>

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Job Detail End -->
{% endblock content %}

jobs/templates/job-list.html
{% extends "base.html" %}
{% load static %}

{% block content %}



<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{title}}</h1>
    </div>
</div>
<!-- Header End -->


<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">{{title}}</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    <div class="job-item p-4 mb-4">
                        <div class="row g-4">
                            {% for job in jobs %}
                            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid border rounded" src="{{job.company_logo.url}}"
                                    alt="" style="width: 80px; height: 80px;">
                                <div class="text-start ps-4">
                                    <h5 class="mb-3">{{job.title}}</h5>
                                    <span class="text-truncate me-3"><i
                                            class="fa fa-map-marker-alt text-primary me-2"></i>{{job.location}}</span>
                                    <span class="text-truncate me-3"><i
                                            class="far fa-clock text-primary me-2"></i>{{job.type}}</span>
                                    <span class="text-truncate me-0"><i
                                            class="far fa-money-bill-alt text-primary me-2"></i>${{job.min_salary}} -
                                        ${{job.max_salary}}</span>
                                </div>
                            </div>

                            <div
                                class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                <div class="d-flex mb-3">
                                    <a class="btn btn-primary" href="{{job.get_absolute_url}}">Detail</a>
                                </div>
                                <small class="text-truncate"><i
                                        class="far fa-calendar-alt text-primary me-2"></i>Deadline:
                                    {{job.deadline}}</small>
                            </div>
                            {%endfor%}
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Jobs End -->
    {% endblock content %}

jobs/templates/job_applied_mail.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Job Applied</title>
    </head>

    <body>
        {% autoescape off %}
        <h3>CareerForge</h3>
        <h4>
            Your application for {{title |safe }} has been submitted successfully.
        </h4>
        <p>If you think, it's not you, then just ignore this email.</p>
        <p>For any Queries or any feedback,</p>
        <p>Email: careerforge@gmail.com</p>

        {% endautoescape %}
    </body>

</html>

jobs/templates/job_status_updated_mail.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Job Status Updated</title>
    </head>

    <body>
        {% autoescape off %}
        <h3>CareerForge</h3>
        <h4>
            Your application has been updated.
        </h4>
        <p>If you think, it's not you, then just ignore this email.</p>
        <p>For any Queries or any feedback,</p>
        <p>Email: careerforge@gmail.com</p>

        {% endautoescape %}
    </body>

</html>

jobs/templates/my-job-list.html
{% extends "base.html" %}
{% load static %}

{% block content %}



<!-- Header End -->
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{title}}</h1>
    </div>
</div>
<!-- Header End -->


<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">{{title}}</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    <div class="job-item p-4 mb-4">
                        <div class="row g-4">
                            {% for application in applications %}
                            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid border rounded"
                                    src="{{application.job.company_logo.url}}" alt=""
                                    style="width: 80px; height: 80px;">
                                <div class="text-start ps-4">
                                    <h5 class="mb-3">{{application.job.title}}</h5>
                                    <span class="text-truncate me-3"><i
                                            class="fa fa-map-marker-alt text-primary me-2"></i>{{application.job.location}}</span>
                                    <span class="text-truncate me-3"><i
                                            class="far fa-clock text-primary me-2"></i>{{application.job.type}}</span>
                                    <span class="text-truncate me-3"><i
                                            class="far fa-money-bill-alt text-primary me-2"></i>${{application.job.min_salary}}
                                        -
                                        ${{application.job.max_salary}}</span>

                                    <span class="text-truncate me-3"><i
                                            class="fas fa-exclamation-triangle text-primary me-2"></i>
                                        {{application.status}}
                                    </span>
                                </div>
                            </div>

                            <div
                                class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                <div class="d-flex mb-3">
                                    <a class="btn btn-primary" href="{{application.job.get_absolute_url}}">Detail</a>
                                </div>
                                <small class="text-truncate"><i
                                        class="far fa-calendar-alt text-primary me-2"></i>Deadline:
                                    {{application.job.deadline}}</small>
                            </div>
                            {%endfor%}
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Jobs End -->
    {% endblock content %}

jobs/templates/post-job.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">{{title}}</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-6">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">{{btn_name}}</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock content %}

</form>

jobs/templates/testimonial-form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h2 class="m-4" style="text-align: center;">Testimonial</h2>
<hr />
<div class="row d-flex align-items-center justify-content-center">
    <div class="col-lg-6">
        <div class="card mb-4">
            {% for message in messages %}

            <div class="alert alert-danger">
                {{ message }}
            </div>

            {% endfor %}
            <form class="m-3" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button class="btn btn-primary">Create Testimonial</button>
                </div>

            </form>
        </div>
    </div>

</div>

{% endblock content %}

</form>